<a href="https://colab.research.google.com/github/syamkumarmuvvala/ML-Assignments/blob/master/NumpyAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment
### Author : Syam Kumar Muvvala

### Question - 01

In [0]:
import numpy as np

In [0]:
def GetVanderMondeMatrix(Matrix, IncreasingOrder):
  if Matrix.ndim > 1:
    rows = Matrix.shape[0]
    cols = Matrix.shape[1]
    N = cols
    RMatrix = np.zeros((rows,cols),dtype=int)
    for i in range(rows):
      for j in range(cols):
        if IncreasingOrder is False:
          RMatrix[i,j] = Matrix[i,j] ** (N-j-1)
        else:
          RMatrix[i,j] = Matrix[i,j] ** (j)
  else:
    rows = Matrix.shape[0]
    N = rows
    RMatrix = np.zeros(rows,dtype=int)
    for i in range(rows):
      if IncreasingOrder is False:
          RMatrix[i] = Matrix[i] ** (N-i-1)
      else:
          RMatrix[i] = Matrix[i] ** (i)
  return RMatrix

In [33]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [34]:
# testing the above function with increasingOrder = True
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
GetVanderMondeMatrix(x,True)

array([[     1,      2,      9,     64,    625],
       [     1,      7,     64,    729,  10000],
       [     1,     12,    169,   2744,  50625],
       [     1,     17,    324,   6859, 160000]])

In [35]:
# testing the above function with increasingOrder = False
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
GetVanderMondeMatrix(x,False)

array([[    1,     8,     9,     4,     1],
       [ 1296,   343,    64,     9,     1],
       [14641,  1728,   169,    14,     1],
       [65536,  4913,   324,    19,     1]])

In [0]:
x = np.arange(100).reshape(25,4)

In [37]:
GetVanderMondeMatrix(x,False)

array([[     0,      1,      2,      1],
       [    64,     25,      6,      1],
       [   512,     81,     10,      1],
       [  1728,    169,     14,      1],
       [  4096,    289,     18,      1],
       [  8000,    441,     22,      1],
       [ 13824,    625,     26,      1],
       [ 21952,    841,     30,      1],
       [ 32768,   1089,     34,      1],
       [ 46656,   1369,     38,      1],
       [ 64000,   1681,     42,      1],
       [ 85184,   2025,     46,      1],
       [110592,   2401,     50,      1],
       [140608,   2809,     54,      1],
       [175616,   3249,     58,      1],
       [216000,   3721,     62,      1],
       [262144,   4225,     66,      1],
       [314432,   4761,     70,      1],
       [373248,   5329,     74,      1],
       [438976,   5929,     78,      1],
       [512000,   6561,     82,      1],
       [592704,   7225,     86,      1],
       [681472,   7921,     90,      1],
       [778688,   8649,     94,      1],
       [884736, 

In [38]:
GetVanderMondeMatrix(np.array([1,2,3,4,5,6]),False)

array([ 1, 16, 27, 16,  5,  1])

In [40]:
GetVanderMondeMatrix(np.array([1,2,3,4,5,6]),True)

array([   1,    2,    9,   64,  625, 7776])

### Question - 02
### Problem : Kth Moving Average

In [0]:
def PrepareNumbersList(inp):
  inplist = inp.split(',')
  Res = []
  for i in inplist:
    Res.append(int(i))
  return Res


In [0]:
def MovingAverage(inpList, k):
  l = len(inpList)
  Res = []
  for i in range(0,l-k+1):
    Res.append(sum(inpList[i:i+k])/k)
  return Res

In [0]:
def FindMovingAverage():
  inp = input("Enter the comma separated list of numbers : ")
  k = int(input("Enter the Window size : "))
  if inp is not "":
    inpList = PrepareNumbersList(inp)
  else:
    return "Invalid List"
  if len(inpList) != 0 and k<len(inpList):
    return MovingAverage(inpList,k)
  else:
    return "Invalid Parameters Given"

#### Applying the Function For Given List

In [44]:
FindMovingAverage()

Enter the comma separated list of numbers : 1,2,3,4,5,6,7,8,9,10
Enter the Window size : 5


[3.0, 4.0, 5.0, 6.0, 7.0, 8.0]

In [46]:
FindMovingAverage()

Enter the comma separated list of numbers : 50
Enter the Window size : 5


'Invalid Parameters Given'

In [47]:
FindMovingAverage()

Enter the comma separated list of numbers : 20,20,12,56,53
Enter the Window size : 2


[20.0, 16.0, 34.0, 54.5]